services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpod-appflyte-licence-service
    ports:
      - "8007:8007"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always